"""Transform that surfaces per-ad-product limits in tool descriptions.

Amazon's API enforces both ``adProductFilter.include.maxItems = 1`` and
per-product ``maxResults`` caps that are LOWER than the schema-declared
``maximum: 5000``. Without this transform, agents reading the schema via
``get_schema`` / ``GetSchemas`` see only the unconditional 5000 and the
generic ``maxItems: 1`` constraint — they discover the real limits the
hard way at call time (B1, F3).

This transform appends a single paragraph generated by
:func:`amazon_ads_mcp.middleware.schema_normalization.render_ad_product_cap_description`
to the description of every tool whose name ends in one of the
ad-product-gated query suffixes (``QueryCampaign``, ``QueryTarget``,
``DSPQueryTarget``, ``SBQueryTarget``, ``SDQueryTarget``).

Single source of truth: the cap table comes from
``_AD_PRODUCT_MAX_RESULTS_CAPS`` in ``schema_normalization.py``; the
suffix list comes from ``_AD_PRODUCT_CAP_TOOL_SUFFIXES`` in the same
module. Drift between description, validator, and the runtime cap check
is structurally impossible.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence

from fastmcp.server.transforms import Transform
from fastmcp.tools.tool import Tool

from ..middleware.schema_normalization import (
    _AD_PRODUCT_CAP_TOOL_SUFFIXES,
    render_ad_product_cap_description,
)

logger = logging.getLogger(__name__)

#: Sentinel substring used to detect when the cap paragraph has already
#: been appended (idempotency under repeated transforms / re-mounts).
_CAP_PARAGRAPH_SENTINEL = "Per-ad-product limits (Amazon Ads API):"


class AdProductCapHintsTransform(Transform):
    """Append per-ad-product cap callout to query-tool descriptions.

    Mirrors the shape of :class:`AsyncHintsTransform` (same sibling
    module): both ``list_tools`` and ``get_tool`` are intercepted so
    description enrichment is reflected by FastMCP's discovery surface
    and by Code Mode's ``GetSchemas`` meta-tool.
    """

    def __init__(self) -> None:
        self._enriched_count = 0

    async def list_tools(self, tools: Sequence[Tool]) -> Sequence[Tool]:
        result = []
        for tool in tools:
            result.append(self._maybe_enrich(tool))
        if self._enriched_count:
            logger.info(
                "AdProductCapHintsTransform: enriched %d tool descriptions "
                "with per-ad-product cap callout",
                self._enriched_count,
            )
        return result

    async def get_tool(self, name, call_next, *, version=None):
        tool = await call_next(name, version=version)
        if tool is None:
            return None
        return self._maybe_enrich(tool)

    def _maybe_enrich(self, tool: Tool) -> Tool:
        if not any(
            tool.name.endswith(suffix) for suffix in _AD_PRODUCT_CAP_TOOL_SUFFIXES
        ):
            return tool
        current_desc = tool.description or ""
        if _CAP_PARAGRAPH_SENTINEL in current_desc:
            return tool
        enriched_desc = current_desc + render_ad_product_cap_description()
        self._enriched_count += 1
        return tool.model_copy(update={"description": enriched_desc})
