blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/KuudoAI/amazon_ads_mcp/blob/main/README.md
    about: Please read the documentation first
  - name: Discussions
    url: https://github.com/KuudoAI/amazon_ads_mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: mailto:security@kuudo.ai
    about: Please report security vulnerabilities privately via email